create table categories
(
    id               integer generated by default as identity
        constraint id_categories_pkey
            primary key,
    name             varchar(255)                 not null,
    amount      integer    default 0 not null,
	upper_category integer

);

create table products
(
    id              integer generated by default as identity
        constraint id_products_pkey
            primary key,
    product_name         varchar(255)           not null,
    company_name            varchar(255)           not null,
    country            varchar(255)           not null,
    amount 				integer default 0,
    price          numeric      default 0         not null,

        condition             varchar(255)          not null,
    category_id   integer      REFERENCES categories(id)         not null

);